### ISSUE TITLE
Animation Editor Broken

### ISSUE THREAD

**Issue by KittyNyu** [CapsAdmin/pac3#539] opened 2017-11-14 00:23 UTC
Animation editor isn't showing up in the context menu anymore and typing animate in console brings it up but I cant do anything in it. Little help please?

**Comment by roboderpy** [comment] 2018-02-26 10:03
Duplicate of https://github.com/CapsAdmin/pac3/issues/535

**Closed by roboderpy** 2018-02-26 10:03 UTC
