### ISSUE TITLE
Player entity model doesn't change

### ISSUE THREAD

**Issue by Danct12** [CapsAdmin/pac3#401] opened 2017-04-25 06:58 UTC
I have a issue with my server, seems like it doesn't happen on other servers, just mine.

When you change a model of your player entity, instead of it being changed, it doesn't change and it'll just use your current player model.

Example should be the scout pac3 in PAC3 examples.
![image](https://cloud.githubusercontent.com/assets/19162768/25372279/f87bed22-29be-11e7-9ca2-0a0467289fc2.png)

Any ideas how to fix this issue? Thanks for advice!

**Comment by Earu** [comment] 2017-04-25 07:06
Is that so for everybody on your server? I see you're using two entities, it is not recommended to do that unless you know what you're doing, it may also be the cause of your playermodel not changing.

**Comment by Danct12** [comment] 2017-04-25 07:26
Not sure if anybody else have this problem on my server, well this PAC came with the PAC3 examples. 

I also tried this with nothing else, just a entity, same thing still happens.
![image](https://cloud.githubusercontent.com/assets/19162768/25373220/f63d347c-29c2-11e7-9017-36eb082734e6.png)

**Comment by Datamats** [comment] 2017-04-25 11:51
Is Team Fortress 2 even mounted on the server?

**Comment by Danct12** [comment] 2017-04-25 13:11
Yes, TF2 is mounted on the server. It's not also caused by TF2 models, I tried this with HL2 ragdolls (see above picture), same thing still happens.

**Comment by roboderpy** [comment] 2017-08-27 07:01
Fixed in develop

**Closed by roboderpy** 2017-08-27 07:01 UTC
