### ISSUE TITLE
MDL downloads does not seek proper textures despite existing on -fastbuild MDLs

### ISSUE THREAD

**Issue by sr229** [CapsAdmin/pac3#1146] opened 2022-01-07 14:46 UTC
- [Model ZIP](https://iastg.s3.ap.cloud-object-storage.appdomain.cloud/stg_1928032180128730.zip).

PAC3 does not know where to look for textures despite existing within the ZIP when the MDL is compiled using -fastbuild.

![image](https://user-images.githubusercontent.com/14976516/148560451-bf87625d-b7e5-441b-a544-47d3803199a2.png)

**Comment by thegrb93** [comment] 2022-01-07 22:29
No idea how fastbuild affects the model, but it could be affecting the mdl's texture path editing code. (Texture paths have to be edited to something unique before mounting in order to not potentially clash with other texture paths).

**Comment by Yagira** [comment] 2022-01-08 00:11
Not sure if this is caused by fastbuild but this model (and some others) have material names that include paths. 
![image](https://user-images.githubusercontent.com/12747052/148619913-012e7197-1830-463e-9f1a-a24c5525b871.png)
It's kinda weird but works in gmod and can be fixed in PAC by just adding the path to the final material path.
![image](https://user-images.githubusercontent.com/12747052/148620385-e1e58742-807e-4396-8045-bdf5d6b3ffcd.png)

**Closed** 2022-02-23 19:08 UTC
