### ISSUE TITLE
sv_pac_webcontent_limit value persistent across servers

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#707] opened 2018-10-01 16:48 UTC
Similar to #284 ?
Multiple people have reported that when they visit servers with sv_pac_webcontent_limit set to anything other than -1 and then switch to another server the value stays the same.

_also why is it sv_pac instead of pac_sv like all the other commands_

**Comment by roboderpy** [comment] 2018-10-02 04:06
Duplicate of #284 and FCVAR_ARCHIVE & FCVAR_REPLICATED is still broken on client. But this bug can be workarounded on PAC3 side.

**Comment by roboderpy** [comment] 2018-10-02 10:08
should be fixed in develop

**Closed by roboderpy** 2018-10-02 10:08 UTC
