### ISSUE TITLE
Crash with submaterials, material parts and urltex

### ISSUE THREAD

**Issue by Cynosphere** [CapsAdmin/pac3#745] opened 2018-12-17 19:42 UTC
![](https://totallynotavir.us/i/lgjyoyld.png)

Model used: `models/workshop/weapons/c_models/c_picket/c_picket.mdl`
Submaterial: index - 2, material - pointed to named material part
Material part: nothing changed except base texture set to a url and a name

Only seems to crash if the material is updated by `pac_urltex_clear_cache` or sometimes changing the URL.

**Comment by Cynosphere** [comment] 2018-12-18 04:46
Version: Latest develop
[Video Demo](https://streamable.com/g6jcj)

If anything I'm starting to think its less of submaterial itself and something with the amount of material parts with urltex (even tho its only 4) and some of them having other values. I only really thought it was the submaterial one that caused that crash because it was the one that would constantly not load properly between changes in map or launching the game period.

**Comment by Jophes** [comment] 2018-12-20 14:34
Sorry, I still can't reproduce this.
If possible, please could you give us the pac in question?
Also, what other addons are you using when this occurs? Can you reproduce this without any addons except pac3 installed, in single player?

**Comment by Cynosphere** [comment] 2018-12-21 02:18
[PAC in question](http://mystb.in/raw/ixorufodiw)

I'm starting to doubt its specifically submaterials but I've crashed people just by wearing this PAC, specifically on chromium branch which may be the suspect more than anything else.

**Comment by roboderpy** [comment] 2018-12-23 01:13
Seems to be race condition, will look into it

**Comment by thegrb93** [comment] 2020-07-19 04:03
Closing in favor of #861

**Closed by thegrb93** 2020-07-19 04:03 UTC
Labels: bug, critical, gmod issue
