### ISSUE TITLE
Glitches. Glitches everywhere.

### ISSUE THREAD

**Issue by Thekingofanimation** [CapsAdmin/pac3#329] opened 2016-10-07 19:30 UTC
So the one. ONE glitch im talking about is the entity glitch. So everytime i add two entities for making 2 weapons not draw to show one model, one of them messes up when they are in a different group. please fix this problem i've been getting very, very frusturated with this problem so please, please fix this.

**Comment by LUModder** [comment] 2016-10-08 20:48
Duplicate of #315 and #322

**Comment by Thekingofanimation** [comment] 2016-10-08 21:18
How can I fix this problem because I always have this problem with entity's.

**Comment by LUModder** [comment] 2016-10-08 21:19
Not use more than one entity part.

**Closed** 2017-01-25 07:38 UTC
Labels: closed to clear my mind. feel free to reopen issue for any reason
