### ISSUE TITLE
Theming issues

### ISSUE THREAD

**Issue by russetdapone** [CapsAdmin/pac3#1018] opened 2021-03-02 11:50 UTC
When using a custom HUD like a darkmode hud, some text isn't dynamic and needs to be made dynamic to the theme. 

![image](https://user-images.githubusercontent.com/32783144/109644442-1a451300-7b1b-11eb-9db8-a944d39c8409.png)
![image](https://user-images.githubusercontent.com/32783144/109644478-216c2100-7b1b-11eb-826e-26011d0bfb1f.png)
![image](https://user-images.githubusercontent.com/32783144/109644499-28932f00-7b1b-11eb-90cf-393863faf2c6.png)

**Comment by CapsAdmin** [comment] 2021-03-05 16:21
not a bug with pac, fixed in garrysmod

https://github.com/Facepunch/garrysmod/pull/1775

**Closed by CapsAdmin** 2021-03-05 16:21 UTC
