### ISSUE TITLE
Non-physical ticked projectiles only renders one at a time

### ISSUE THREAD

**Issue by TheReeb** [CapsAdmin/pac3#888] opened 2020-05-16 14:31 UTC
![projectile stuff](https://user-images.githubusercontent.com/65454681/82121804-0f89df00-9790-11ea-94c2-889bdffd76af.png)
As the title says, unless you tick the "physical" setting on a projectile, it will only render 1 at a time. I have provided a picture above and an example outfit below to demonstrate (FYI: red ball is physical, blue ball is non-physical)). 

It is worth noting that while the blue ball only renders 1 at a time, it STILL exists until it expires.

Example outfit: https://www.dropbox.com/s/ibhj8vp0luqyxel/projectile%20outfit%20problem.txt?dl=0

**Comment by thegrb93** [comment] 2020-05-16 20:48
Looks like the problem is pac.HookEntityRender uses ent:EntIndex() and clientside entities all have the same index of -1.

**Comment by thegrb93** [comment] 2020-05-16 22:36
I'll test the fix out in a little while

**Comment by thegrb93** [comment] 2020-05-17 05:20
Fixed in develop.

**Closed** 2020-05-17 05:20 UTC
Labels: bug
