### ISSUE TITLE
issue with legacy Entity and the new Entity2 parts, they cause GetModel() to go out-of-sync between the Client and the Server

### ISSUE THREAD

**Issue by CapsAdmin** [CapsAdmin/pac3#523] opened 2017-11-06 16:15 UTC
Hazbelll - 10/13/2017
Also another issue with legacy Entity and the new Entity2 parts, they cause GetModel() to go out-of-sync between the Client and the Server.

How to reproduce:

1. Add an Entity part to PAC.
2. Change the model field to, for example: models/props_c17/furnitureStove001a.mdl
3. Delete the PAC and your Player Model should revert to its usual model.
4. Print the model using Entity:GetModel() on the Server. It should return the current model correctly.
5. Print the model using Entity:GetModel() on the Client. It should not return the current model, but the one you set via PAC.

**Comment by roboderpy** [comment] 2017-11-06 16:25
Entity2 just causes model desync in general. Model changes on all clients, but the server stays with same model causing top notch both visual and logical issues

**Comment by roboderpy** [comment] 2017-11-10 10:39
![aaaaaAAAAAAAAAAAA](https://i.dbot.serealia.ca/2017/11/92ed3185b6_hl2_2017-11-10_17-36-00.png)

**Comment by thegrb93** [comment] 2018-01-08 05:53
I tried reproducing this issue but couldn't. One thing I think should change though is deleting the entity part should revert the player's model to normal.

**Comment by thegrb93** [comment] 2018-01-08 06:21
I found whenever an entity with custom model enters PVS and triggers 'NotifyShouldTransmit', the model that is rendered goes back to whatever the server's value is, however GetModel() will still return the set custom model.

Further, SetModel again on the entity to return it to the custom model will not work since the lua state thinks it's already that model (even though the original model is being rendered).

**Comment by thegrb93** [comment] 2018-01-08 06:27
When the server's model modifier is enabled, it doesn't seem to be a problem with players since it sets their model serverside.

**Comment by thegrb93** [comment] 2018-01-08 06:36
Another issue is removing the Entity part will not clear whatever custom model the player or entity is set to.

**Comment by roboderpy** [comment] 2018-02-26 10:05
this was fixed in two commits before, both from me and @thegrb93

**Closed by roboderpy** 2018-02-26 10:05 UTC
