### ISSUE TITLE
My Pac is being cleared?!

### ISSUE THREAD

**Issue by PeroxideHarp** [CapsAdmin/pac3#716] opened 2018-10-28 13:13 UTC
I̶'̶m̶ ̶n̶o̶t̶ ̶s̶u̶r̶e̶ ̶i̶f̶ ̶t̶h̶i̶s̶ ̶i̶s̶ ̶r̶e̶l̶a̶t̶e̶d̶ ̶t̶o̶ ̶t̶h̶i̶s̶ ̶i̶s̶s̶u̶e̶,̶ ̶b̶u̶t̶ ̶I̶'̶v̶e̶ ̶r̶e̶c̶e̶n̶t̶l̶y̶ ̶b̶e̶e̶n̶ ̶p̶l̶a̶y̶i̶n̶g̶ ̶a̶r̶o̶u̶n̶d̶ ̶w̶i̶t̶h̶ ̶A̶n̶i̶m̶a̶t̶i̶o̶n̶ ̶E̶d̶i̶t̶o̶r̶ ̶s̶i̶n̶c̶e̶ ̶a̶ ̶c̶o̶u̶p̶l̶e̶ ̶o̶f̶ ̶d̶a̶y̶s̶ ̶a̶g̶o̶ ̶a̶n̶d̶ ̶o̶f̶ ̶j̶u̶s̶t̶ ̶r̶e̶c̶e̶n̶t̶l̶y̶ ̶w̶h̶e̶n̶e̶v̶e̶r̶ ̶I̶ ̶g̶o̶ ̶t̶o̶ ̶"̶w̶e̶a̶r̶"̶ ̶m̶y̶ ̶P̶a̶c̶ ̶i̶t̶ ̶j̶u̶s̶t̶ ̶g̶e̶t̶s̶ ̶c̶l̶e̶a̶r̶e̶d̶ ̶f̶r̶o̶m̶ ̶t̶h̶e̶ ̶m̶e̶n̶u̶.̶ ̶I̶'̶v̶e̶ ̶t̶r̶i̶e̶d̶ ̶w̶e̶a̶r̶i̶n̶g̶ ̶a̶ ̶P̶a̶c̶ ̶t̶h̶a̶t̶ ̶d̶o̶e̶s̶n̶'̶t̶ ̶h̶a̶v̶e̶ ̶a̶n̶ ̶A̶n̶i̶m̶a̶t̶i̶o̶n̶ ̶i̶n̶ ̶i̶t̶ ̶b̶u̶t̶ ̶n̶o̶t̶h̶i̶n̶g̶,̶ ̶I̶'̶v̶e̶ ̶a̶l̶s̶o̶ ̶t̶r̶i̶e̶d̶ ̶r̶e̶i̶n̶s̶t̶a̶l̶l̶i̶n̶g̶ ̶t̶h̶e̶ ̶P̶a̶c̶3̶ ̶a̶d̶d̶o̶n̶ ̶b̶u̶t̶ ̶s̶t̶i̶l̶l̶ ̶n̶o̶t̶h̶i̶n̶g̶.̶ ̶I̶'̶m̶ ̶n̶o̶t̶ ̶s̶u̶r̶e̶ ̶w̶h̶a̶t̶ ̶c̶o̶u̶l̶d̶ ̶b̶e̶ ̶c̶a̶s̶u̶i̶n̶g̶ ̶i̶t̶,̶ ̶I̶'̶m̶ ̶h̶o̶p̶i̶n̶g̶ ̶t̶h̶a̶t̶ ̶s̶o̶m̶e̶o̶n̶e̶ ̶h̶e̶r̶e̶ ̶d̶o̶e̶s̶

Edit: I've seemed to of fixed it by messing around with the menu in Utilities. Sorry, but im not too sure how to delete this post.

**Comment by thegrb93** [comment] 2018-10-28 20:37
It's a lot harder to read with that odd font. Try not to do that. If you want underline, you can use __underline text__ with `__hi__`

**Comment by thegrb93** [comment] 2018-10-28 20:38
Guess github is different then. Idk. Closing since you figured it out.

**Comment by AnyaOQuinn** [comment] 2018-11-05 17:06
Randomly happens on my server to people, usually rejoining fixes it but this is still a regular issue. Has been happening since the obfuscation change.

**Comment by thegrb93** [comment] 2018-11-05 18:11
Does the server have any form of anticheat?

**Comment by AnyaOQuinn** [comment] 2018-11-05 18:13
Nope. Not yet, anyway. 😂

**Comment by thegrb93** [comment] 2018-11-05 19:33
When a player's pac gets cleared, does it clear for everyone or can others still see it while others can't.

**Comment by AnyaOQuinn** [comment] 2018-11-05 19:42
In one case, they could still see it.  I haven't extensively tested it but I have had it happen to me and others have had it happen to them.

**Comment by thegrb93** [comment] 2018-11-05 20:13
If you can find out if some players still see it while others don't, that might help us figure out the issue.

If nobody can see it, that information would also help.

**Comment by AnyaOQuinn** [comment] 2018-12-12 14:32
At least that's one situation where panicking solved the issue.

**Comment by Reypenber** [comment] 2018-12-15 08:17
i have the same problem where when  click wear my pac clears but people can see it and i cant, i also cant use it

**Comment by roboderpy** [comment] 2018-12-23 02:12
I addressed some changes to fix up this issue, but i've never been able to reproduce this by myself, but i know others who were reporting the same issue, but only before https://github.com/CapsAdmin/pac3/commit/c616e15e98b2da76e40bb7fa5ec856b93d0c89dc

**Closed by roboderpy** 2018-12-23 02:12 UTC
Labels: not enough information
