### ISSUE TITLE
Pacs in multiplayer disappear when I (or anyone else) dies.

### ISSUE THREAD

**Issue by Fred-FredBurger** [CapsAdmin/pac3#296] opened 2016-06-16 22:41 UTC
Basically whenever I suicide or just die in general, any death events I made and even my pac itself doesn't appear, its just gone.. poof. Same when other players die or just suicide, nothing, nada... zip. 
Nothing plays at death either, no sounds, no random bits hanging around, just the ragdoll floppin on over like the pac event was set to make everything hide the moment they die.

The only time this isn't a thing is if I'm in single player... I'm not sure why that happens.. it's so weird.

**Comment by LUModder** [comment] 2016-06-16 22:58
Duplicate of #270

**Closed** 2016-06-26 10:58 UTC
