### ISSUE TITLE
using pac_restart on the workshop version throws an error

### ISSUE THREAD

**Issue by JitZub** [CapsAdmin/pac3#1171] opened 2022-03-09 06:14 UTC
[PAC3] lua/pac3/editor/client/logic.lua:55: Tried to use a NULL entity!
  1. EyePos - [C]:-1
   2. Call - lua/pac3/editor/client/logic.lua:55
    3. OpenEditor - lua/pac3/editor/client/init.lua:148
     4. unknown - lua/autorun/pac_restart.lua:230
      5. unknown - lua/includes/modules/concommand.lua:54

this error happens consistently when using pac_restart

**Comment by thegrb93** [comment] 2022-03-09 07:58
Looks like it's caused by https://github.com/CapsAdmin/pac3/commit/9c69b2f24eac712392ebb9fe307f12ef92c3b369

**Comment by CapsAdmin** [comment] 2022-03-09 08:23
> Looks like it's caused by [9c69b2f](https://github.com/CapsAdmin/pac3/commit/9c69b2f24eac712392ebb9fe307f12ef92c3b369)

Can this somehow not work?

https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/core/client/init.lua#L60-L64

**Comment by thegrb93** [comment] 2022-03-09 08:30
The problem is pac_restart is causing the var to get reset to NULL.

**Comment by CapsAdmin** [comment] 2022-03-09 21:58
That makes sense. Fixed in develop.

**Closed by CapsAdmin** 2022-03-09 21:58 UTC
Labels: bug
