### ISSUE TITLE
Death ragdollize parent not properly unsetting part.draw_hidden part 2

### ISSUE THREAD

**Issue by Zeni44** [CapsAdmin/pac3#909] opened 2020-05-31 03:35 UTC
Same issue as #900 however with a different cause. 

When the ragdoll with the applied pac manages to go beyond your drawing distance and the person's player entity remains within your drawing distance **and** respawns to a nearby spawnpoint/revive mechanics or similar that is still within your distance, the pac does not get unhidden on the player.

Pretty sure it's unrelated to the fix provided and just another issue with the feature itself even if it's unlikely to occur.

**Comment by thegrb93** [comment] 2020-05-31 04:12
I'm thinking the root cause is the player's outfit isn't getting unhidden when they respawn. Can revert https://github.com/CapsAdmin/pac3/commit/b5eb80a78b90c86f919cdd471df429f46ee4a8c1 and fix the root cause if that's the case.

**Comment by thegrb93** [comment] 2020-05-31 04:13
Not entirely sure about reverting that though.

**Comment by CapsAdmin** [comment] 2021-01-24 19:09
Is this fixed now? 

I don't remember any of this code, but it looks to me like there's nothing that changes the outfit back to the original owner again.

**Comment by thegrb93** [comment] 2021-01-24 23:02
No, I never fully figured it out. This is mostly just refactoring.

**Comment by thegrb93** [comment] 2021-01-24 23:04
https://github.com/CapsAdmin/pac3/pull/910 feel free to close it if it's been obsoleted.

**Comment by Zeni44** [comment] 2021-01-25 07:04
Seems fixed!

**Closed** 2021-01-25 07:22 UTC
Labels: bug
