### ISSUE TITLE
player entities not changing to designated model

### ISSUE THREAD

**Issue by KabusIblis** [CapsAdmin/pac3#456] opened 2017-08-02 22:14 UTC
wierd stuff happening, @Tenrys probably has more details

**Comment by Tenrys** [comment] 2017-08-02 23:15
entity part with model parameter set doesn't do anything at all, tested in singleplayer

**Comment by roboderpy** [comment] 2017-08-27 12:32
Duplicate of https://github.com/CapsAdmin/pac3/issues/401

**Closed by roboderpy** 2017-08-27 12:32 UTC
