### ISSUE TITLE
Bug on the arm

### ISSUE THREAD

**Issue by MiojoDeFrango** [CapsAdmin/pac3#363] opened 2017-01-23 18:16 UTC
When I put an item on my arm and move away, the items on my head do not fall off, but my arm does. Is it a bug just for my camera and do others see it normally or not?
![20170123160009_1](https://cloud.githubusercontent.com/assets/25305329/22216672/2a8684ce-e187-11e6-9283-c967209c9a76.jpg)
![20170123160011_1](https://cloud.githubusercontent.com/assets/25305329/22216673/2a8b48ec-e187-11e6-975e-eeb2f0a86a5e.jpg)

**Comment by CapsAdmin** [comment] 2017-01-23 19:52
if you add the entity part and set "lod" to 0 does that fix it?

**Comment by CapsAdmin** [comment] 2017-01-25 07:43
closing because this seems like a question and not a bug and you sorted it out

**Closed by CapsAdmin** 2017-01-25 07:43 UTC
Labels: question
