### ISSUE TITLE
Error when a custom animation is selected in editor

### ISSUE THREAD

**Issue by MadMatty57** [CapsAdmin/pac3#469] opened 2017-08-24 23:13 UTC
`[PAC3] lua/pac3/editor/client/animation_timeline.lua:114: attempt to index a nil value
  1. EditBone - lua/pac3/editor/client/animation_timeline.lua:114
   2. SelectKeyframe - lua/pac3/editor/client/animation_timeline.lua:167
    3. Load - lua/pac3/editor/client/animation_timeline.lua:133
     4. Open - lua/pac3/editor/client/animation_timeline.lua:257
      5. v - lua/pac3/editor/client/animation_timeline.lua:270
       6. Run - lua/includes/modules/hook.lua:84
        7. Call - lua/pac3/editor/client/init.lua:248
         8. DoClick - lua/pac3/editor/client/panels/tree.lua:237
          9. InternalDoClick - lua/pac3/editor/client/panels/pac_tree.lua:166
           10. DoClick - lua/pac3/editor/client/panels/pac_tree.lua:140
            11. unknown - lua/vgui/dlabel.lua:232`

The game would throw this error whenever I try to click or select the custom animation entity.

**Comment by roboderpy** [comment] 2017-08-25 01:16
Duplicate of https://github.com/CapsAdmin/pac3/issues/427

**Closed** 2017-08-26 12:14 UTC
