### ISSUE TITLE
Wearing pac outfit doesn't work

### ISSUE THREAD

**Issue by Dekosem** [CapsAdmin/pac3#597] opened 2018-03-04 13:44 UTC
Anyone knows what happened? the issue started i believe yesterday and on newest version of pac like on metaconstruct i can't wear anything

**Comment by roboderpy** [comment] 2018-03-04 23:29
Duplicate of https://github.com/CapsAdmin/pac3/issues/596

**Closed by roboderpy** 2018-03-04 23:29 UTC
