### ISSUE TITLE
Conflict with dLib

### ISSUE THREAD

**Issue by ZarbleBapkins** [CapsAdmin/pac3#530] opened 2017-11-08 03:34 UTC
Whenever I play the game with PAC3 and dLib this error appears in the console:

[ERROR] lua/pac3/editor/client/wear.lua:180: attempt to perform arithmetic on upvalue 't' (a boolean value)
1. nextevent - lua/pac3/editor/client/wear.lua:180
2. unknown - lua/dlib/modules/hook.lua:557

I also suspect that this may be the reason why I am stuck in first person while in the editor.

**Comment by roboderpy** [comment] 2017-11-08 03:56
Duplicate of https://github.com/CapsAdmin/pac3/issues/529 ; Fixed in develop

**Comment by roboderpy** [comment] 2017-11-08 03:57
Also, this doesn't happen on current github version (master)

**Closed by roboderpy** 2017-11-08 03:56 UTC
