### ISSUE TITLE
Models that have been added on or bonemerged spasm around during movement.

### ISSUE THREAD

**Issue by ChayseRamsay** [CapsAdmin/pac3#250] opened 2016-01-26 20:45 UTC
As mentioned in the title, moving around with a model or really anything attached to a playermodel using pac, or even bonemerged, causes the attached model to glitch and spasm around during said movement, instead of staying attached to the playermodel. It seems it either lags slightly behind the player or is just generally jittery. I'll try and get a recording of it.

Gamemode: Nutscript, Custom Schema
Addons that could be causing interference: http://steamcommunity.com/sharedfiles/filedetails/?id=606243850

**Comment by LUModder** [comment] 2016-01-26 20:49
Check translucent on the bonemerged model.

**Comment by ChayseRamsay** [comment] 2016-01-26 20:58
That might work for bonemerged models, but it definitely doesn't work for models I've simply attached to a bone, such as a backpack. They still jitter around during movement, which didn't happen when I last used pac. It's not just me, either, it's pretty much everyone on my server.

**Comment by Kamshak** [comment] 2016-01-27 15:10
I know that uTime can cause this, don't know how/why though

**Comment by LUModder** [comment] 2016-01-27 15:21
UTime shouldn't affect it, you don't know what you're talking about.

**Comment by Kamshak** [comment] 2016-01-27 17:24
I know very well what i am talking about. Don't make statements like that without even testing it. Makes you a dick.

**Comment by LUModder** [comment] 2016-01-27 18:03
Something that only has to do with storing player data shouldn't interact
with clientside models. You're the one making yourself look bad tbh

**Comment by Kaosheaven** [comment] 2016-01-27 18:09
Ummm how about you don't go around acting like a self centered asshole and claim something like utime which is entirely server based not to mention not on a lot of servers the number is so low I can count it on my fingers and get a computer that isn't a toaster

**Comment by CapsAdmin** [comment] 2016-01-27 18:33
If I had to guess what in utime that would cause this it would have to be

https://github.com/TeamUlysses/utime/blob/master/lua/autorun/cl_utime.lua#L159-L166

I had a similar issue with my thirdperson camera. Somehow shooting a trace at your player clientside messes bone positions up. Probably something to do with prediction but I don't see any reason for it to happen.

**Comment by LUModder** [comment] 2016-01-27 18:39
UTime won't do that and your third person camera must be shitly coded
apposed to STP and CTP

**Comment by LUModder** [comment] 2016-01-27 18:39
Eek didn't read who sent that whoops

**Comment by ChayseRamsay** [comment] 2016-01-27 18:55
I have both uTime and SimpleThirdPerson. If you want temporary access to my server, Caps, I'm happy to quickly make a subuser for you to take a look at the code n' stuff.

**Comment by CapsAdmin** [comment] 2016-01-27 19:15
@LUModder hahahha
Well I fixed it in CTP by deferring the trace if I recall correctly. You could most likely fix utime as well.

@ChayseRamsay  It can be a lot of addons. You could override util.TraceLine to be empty and see if that fixes it, if it does then it might be easier to track down which addons it is.

**Comment by ChayseRamsay** [comment] 2016-01-27 19:31
How do I override that exactly? GLua isn't exactly my speciality. I prefer Python, myself.

**Comment by CapsAdmin** [comment] 2016-01-27 19:34
sv_allowcslua 1 (i think)

lua_run_cl local old = util.TraceLine; util.TraceLine = function(...) local ret = old(...) if ret.Entity == LocalPlayer() then debug.Trace() end return ret end

that should spam your console if there's a trace that's hitting the localplayer which i think causes this problem

**Comment by ChayseRamsay** [comment] 2016-01-27 19:36
Unknown command: util.TraceLine

**Comment by Kaosheaven** [comment] 2016-01-27 19:48
Sorry about exploding

**Comment by CapsAdmin** [comment] 2016-01-27 19:53
remove the ; i think

**Comment by ChayseRamsay** [comment] 2016-01-27 21:12
Nothing happened.

**Comment by ChayseRamsay** [comment] 2016-01-27 21:14
Line 416 of cl_hooks.lua, apparantly.

`function GM:CalcViewModelView(weapon, viewModel, oldEyePos, oldEyeAngles, eyePos, eyeAngles)
	if (!IsValid(weapon)) then
		return
	end

	local client = LocalPlayer()

	local data = {}
		data.start = eyePos + client:GetAimVector() * 1
		data.endpos = eyePos + client:GetAimVector() * 30
	local trace = util.TraceLine(data)

	viewModel:SetPos(trace.HitPos - client:GetAimVector()*18 * 1.3)

	local value = 0

	if (!client:WepRaised()) then
		value = 100
	end

	local fraction = (client.raisedFrac or 0) / 100
	local rotation = weapon.LowerAngles or Angle(30, 5, -10)
	
	eyeAngles:RotateAroundAxis(eyeAngles:Up(), rotation.p * fraction)
	eyeAngles:RotateAroundAxis(eyeAngles:Forward(), rotation.y * fraction)
	eyeAngles:RotateAroundAxis(eyeAngles:Right(), rotation.r * fraction)

	client.raisedFrac = math.Approach(client.raisedFrac or 0, value, FrameTime() * 150)

	viewModel:SetAngles(eyeAngles)

	if (weapon.GetViewModelPosition) then
		local position, angles = weapon:GetViewModelPosition(eyePos, eyeAngles)

		oldEyePos = position or oldEyePos
		eyeAngles = angles or eyeAngles
	end
	
	if (weapon.CalcViewModelView) then
		local position, angles = weapon:CalcViewModelView(viewModel, oldEyePos, oldEyeAngles, eyePos, eyeAngles)

		oldEyePos = position or oldEyePos
		eyeAngles = angles or eyeAngles
	end

	return oldEyePos, eyeAngles
end`

**Comment by Kamshak** [comment] 2016-01-28 18:18
@LUModder @Kaosheaven i apologize shouldnt snap when trolls post. I wrote Pointshop2 and i'm very well aware of how the shop and lua works (sure had to "read lua and look through files" to do a full pac integration). A little info for you: Pointshop2 uses PAC as rendering engine and is used by ~600 servers. Now some of those using the shop have had the same problem, often in conjunction with uTime. Removing it fixed the problem. I do not know the underlying cause, however  uTime is not a 100% serveside addon (might not even be the addon alone but rather a combination of addons).

Now even if i don't know what i was talking about it's generally not a good idea to bash people who are trying to help without even looking into their observations and just blindly putting them down as idiots. Very discouraging and extremely unhelpful, even more so when you do not actually have a solution or any idea what is causing the problem yourself.

Sorry for offtopic.

**Comment by Kaosheaven** [comment] 2016-01-28 20:04
A I'm not a troll 
B pointshop may use the same render engine but almost everything else was stripped off and made different
C I'm sorry too shouldn't have hopped in

**Comment by BAPEsta** [comment] 2016-02-02 23:57
I have this same issue, I have Pointshop 2. I removed my third person mod and also uTime and there is no difference. For some odd reason if you change the bone the model is linked to to eyes instead of head it fixes it. Either way, this doesn't work for spine, ect. SOMEONE PLEASE fix this bug my it's a headache.

**Comment by Kaosheaven** [comment] 2016-02-03 15:43
Make sure it isn't the update that borked your pointshop 2/PAC

**Comment by BAPEsta** [comment] 2016-02-06 04:18
So what is the update now, what do we do to fix this?

**Comment by LUModder** [comment] 2016-02-06 16:57
Honestly, it's really weird the results people have been getting after the update. Meta and FlexBox work fine but a lot of other servers don't for some reason. Something experimental that Caps was working on might of gotten into the workshop version on accident or something, cause that's all I can think of that would of happened, since everything works fine with the github version.

**Comment by BAPEsta** [comment] 2016-02-07 23:37
I'm not using the Workshop version and indeed the Github instead, for some reason though it still has the issue. I'm dying for a fix for this as this is Server Breaking for my server. If there is any addon that I have in my workshop collection that could possibly conflict, let me know. I have removed all scriptfodder scripts and none of them was the cause, including uTime. Please, need this fix badly! http://steamcommunity.com/sharedfiles/filedetails/?id=596508874

**Comment by LUModder** [comment] 2016-02-08 00:15
What's the problem with PAC though?

**Comment by BAPEsta** [comment] 2016-02-08 00:39
Whenever looking at other players, their PAC3 items move around, lag, spasm, and flicker. When I look at my character through the Camera tool it is just fine and stays attached as it should.

**Comment by CapsAdmin** [comment] 2016-02-08 15:10
One way to work around this in pac is to not use `local pos, ang = ent:GetBonePosition(id)` and use `local mat = ent:GetBoneMatrix(id) local pos, ang = mat:GetTranslation(), mat:GetAngles()` instead. When I tried doing this it broke a lot of outfits so I don't know what to do about it. 

The real issue IMO is that GetBonePosition acts weird when util.TraceLine hits the entity that pac gets the bone positions from. So most likely GetBonePosition should be fixed in gmod itself unless there's some explicit documented reason in source engine not to use it under some circumstances.

I didn't remember at first but this is related to #107. Continue discussion there.

**Closed by CapsAdmin** 2016-02-08 15:10 UTC
