### ISSUE TITLE
Parenting to special pac bones makes entities "blink"

### ISSUE THREAD

**Issue by unknao** [CapsAdmin/pac3#1174] opened 2022-03-13 20:34 UTC
Ive made shoulderguards for a pac that ive parented to the "shoulder" bones and they seem to be sometimes exhibiting a "blinking" behavior, afaik this does not happen on the default ValveBiped bones.
![gmod_IvxN125B7G](https://user-images.githubusercontent.com/24782457/158078139-11ec1b3a-818d-4445-981a-014056b1ee43.gif)

**Comment by thegrb93** [comment] 2022-03-14 01:06
Seems like a problem with the playermodel. The shoulder bones are flickering to the origin pos. I don't know what models have a 'shoulder' bone so I can't test it myself.

**Comment by unknao** [comment] 2022-03-15 09:41
The problem seems to happen on servers that have been running for a long time, and the model with the shoulder bones that i use is the rebel malo06.

**Comment by thegrb93** [comment] 2022-03-15 10:46
All I know is that it is a 'helper' bone and helper bones are semi-procedural. Here's a list of them https://github.com/robotboy655/gmod-animations/blob/master/humans_sdk/lowesthumannohelpers.qci .

Do you know if this is something that's started happening after a recent update? I am kind of suspecting it to be a source engine problem otherwise.

**Comment by Yagira** [comment] 2022-03-15 14:20
There are multiple versions of this problem that existed for years, there might be some new ones related to this but most of them were always there.

1. Simply adding a model to one of these bones will move it to 'invalidbone' when the LOD changes. (
Video: https://i.imgur.com/XxTX9e3.mp4
Outfit: [prop.txt](https://github.com/CapsAdmin/pac3/files/8253956/prop.txt)

2. Using an entity and a model works differently depending on where the model is.

    - Adding a model to a group different than the entity will randomly switch between the correct position and 'invalidbone'. This might because the entity forces LOD0 by default which seems to fix the problem but I guess it depends on which part loads first.
    Video: https://i.imgur.com/1lHCRok.mp4
    Outfit: [different_group.txt](https://github.com/CapsAdmin/pac3/files/8253949/different_group.txt)
    
    - Adding a model to the entity will attach it to the origin of the entity part rather than the selected bone. This one might actually be caused by some of the recent changes. There was also a similar problem with bones that got fixed not so long ago.
    Image: https://i.imgur.com/3GUwqFS.jpg
    Outfit: [ent+mod.txt](https://github.com/CapsAdmin/pac3/files/8254100/ent%2Bmod.txt)
    
    - Placing a model in the same group as the entity but not attached directly to the entity seems to work.
    Video: https://i.imgur.com/zgpe8vs.mp4
    Outfit: [same_group.txt](https://github.com/CapsAdmin/pac3/files/8254133/same_group.txt)
    
Maybe that will point you onto something.

**Comment by thegrb93** [comment] 2022-03-15 21:51
Yeah, the model mesh isn't the only thing with LOD, the skeleton has LOD too. Most notably, the fingers. This looks more like an issue with the animation; perhaps related to the CurTime precision since he mentioned it happening after a long time

**Comment by thegrb93** [comment] 2022-03-15 21:53
I can look into it some more as well as the other issues you posted, just to see what changes started causing them.

**Comment by thegrb93** [comment] 2022-03-16 23:07
> There are multiple versions of this problem that existed for years, there might be some new ones related to this but most of them were always there.
> 
> 1. Simply adding a model to one of these bones will move it to 'invalidbone' when the LOD changes. (
>    Video: https://i.imgur.com/XxTX9e3.mp4
>    Outfit: [prop.txt](https://github.com/CapsAdmin/pac3/files/8253956/prop.txt)
> 2. Using an entity and a model works differently depending on where the model is.
>    
>    * Adding a model to a group different than the entity will randomly switch between the correct position and 'invalidbone'. This might because the entity forces LOD0 by default which seems to fix the problem but I guess it depends on which part loads first.
>      Video: https://i.imgur.com/1lHCRok.mp4
>      Outfit: [different_group.txt](https://github.com/CapsAdmin/pac3/files/8253949/different_group.txt)
>    * Adding a model to the entity will attach it to the origin of the entity part rather than the selected bone. This one might actually be caused by some of the recent changes. There was also a similar problem with bones that got fixed not so long ago.
>      Edit: This actually affects all parts and you can work around it by adding a bone part between the entity and the part that you want.
>      Image: https://i.imgur.com/3GUwqFS.jpg
>      Outfit: [ent+mod.txt](https://github.com/CapsAdmin/pac3/files/8254100/ent%2Bmod.txt)
>    * Placing a model in the same group as the entity but not attached directly to the entity seems to work.
>      Video: https://i.imgur.com/zgpe8vs.mp4
>      Outfit: [same_group.txt](https://github.com/CapsAdmin/pac3/files/8254133/same_group.txt)
> 
> Maybe that will point you onto something.

@Yagira could you open new issues with those? If any are duplicate, I'll close the other since these have testable examples.

**Comment by Yagira** [comment] 2022-03-16 23:32
Posted separate issues for them.

**Comment by thegrb93** [comment] 2022-03-16 23:35
Thanks

**Comment by thegrb93** [comment] 2022-03-19 01:39
Going to close this one in favor of https://github.com/CapsAdmin/pac3/issues/1180

**Closed by thegrb93** 2022-03-19 01:39 UTC
Labels: not enough information, unable to reproduce
