### ISSUE TITLE
Bodygroups have stopped working entirely

### ISSUE THREAD

**Issue by Kiruclanz** [CapsAdmin/pac3#395] opened 2017-04-15 16:50 UTC
I don't know if it was a pac update or a gmod update that broke it, but bodygroups don't work anymore in pac 3.

**Comment by roboderpy** [comment] 2017-08-27 08:47
Duplicate of https://github.com/CapsAdmin/pac3/issues/374

**Closed by roboderpy** 2017-08-27 08:47 UTC
