### ISSUE TITLE
Button Events linked to Toggled events (E.G Is on ground) do not function properly upon switching

### ISSUE THREAD

**Issue by Logzombie** [CapsAdmin/pac3#882] opened 2020-04-23 21:55 UTC
Bit hard to make a proper title on this one. But long story short, having a button event inside of a group parented to a different event (in this case, Is on ground) and triggering upon the same button, causes some weirdness. 

Upon first trying the event after wear, the first tried will function as intended. Once the Is on ground event is triggered otherwise, say when the button event is triggered in the air, it will not play out as intended for the first, or in this case, even the second attempt, usually resulting in key parts of the event tree being almost entirely skipped, including proper timerx execution, animation parts or sound parts, etc.

![image](https://user-images.githubusercontent.com/50374409/80153184-005ea980-85b5-11ea-8cc2-75dda688cc03.png)

See Video for live result (This shit plagued me ever since the end of 2018): https://dl.dropboxusercontent.com/s/i6zgrz9ptcq3dwp/Desktop%202020.04.23%20-%2022.40.46.02.compressed.mp4

**Comment by thegrb93** [comment] 2020-05-12 05:31
Minimal reproduction examples are a developer's best friend. I didn't write any of pac3 so it's impossible for me to know what the problem is, but I can debug the problem if I have a malfunctioning outfit. Please provide a simple example of the malfunctioning outfit.

**Comment by thegrb93** [comment] 2020-05-18 00:34
@Logzombie

**Comment by thegrb93** [comment] 2020-05-20 14:45
@Logzombie

**Comment by Logzombie** [comment] 2020-07-14 12:01
Forgive me for the incredibly late response, been sorting out health related issues and other important junk.

@thegrb93 
[firetest.txt](https://github.com/CapsAdmin/pac3/files/4918604/firetest.txt)

Toggles: Is on ground for both events. Hold R to play the full event. If flames are coming out of the top of the player's head, the event is functioning as intended. If the ground version works, the air version doesn't (at least from my experience, with little way around it). As the video has shown, using said event in the air after using it on the ground takes about 3 attempts of holding R to get it fully functioning again.

**Comment by thegrb93** [comment] 2020-07-14 14:36
No worries. Thanks for the example. I may have time today to work on glua stuff.

**Comment by thegrb93** [comment] 2020-07-16 06:00
Postponing to weekend. Too much work

**Comment by thegrb93** [comment] 2020-07-19 05:22
Seems to have something to do with the events' timers not resetting or still running while they are hidden.

**Comment by DBotThePony** [comment] 2020-07-19 05:54
Will look into it (since i did changes to events and how they affect other parts some time ago)

**Comment by thegrb93** [comment] 2020-07-19 05:55
![image](https://user-images.githubusercontent.com/6713261/87868359-e1c54000-c962-11ea-8be0-4aacabbb13d7.png)

**Comment by thegrb93** [comment] 2020-07-20 01:07
@DBotThePony might be related to https://github.com/CapsAdmin/pac3/issues/881

**Comment by DBotThePony** [comment] 2020-07-23 14:33
I confirm that i can reproduce the issue with PAC given

**Comment by Yagira** [comment] 2020-07-23 15:43
You forgot "affect children only" on the **is_on_ground** events. Don't know if the fact that you actually need them is a bug or not, but the problem gets fixed once you check them. Honestly all events should have that setting checked by default, I'd even say it should be hidden from players/removed. Trying to use events on their parents always causes problems and is almost never actually needed.

**Comment by Yagira** [comment] 2020-07-23 15:52
Here's a video showing that it actually works. 
https://drive.google.com/file/d/1w_GTpUYLETLet6vL4wfvVWOde_7LPha0/view

**Comment by DBotThePony** [comment] 2020-07-23 15:56
@Yagira yes, it work as expected as long as **you don't let the event finish**. After you finish fire breathing, trying to do the same **after** you touched the ground/flew away (obviously, with also full event finish) it won't work properly for first time.

**Comment by DBotThePony** [comment] 2020-07-23 15:58
I could actually *break* TimerX behavior in other cases with my last commit, please check it out.

**Comment by Yagira** [comment] 2020-07-23 16:03
@DBotThePony thats simply not true, it works no matter what, i can wait till the event is over, i can hold the key for 5 minutes, it doesn't matter, it just works

**Comment by Yagira** [comment] 2020-07-23 16:15
@DBotThePony I checked the latest version with your commit. And:
1.When ``is_on_ground`` has ``affect children only`` **UNCHECKED** it works but also causes the events to re-trigger. In the case, if you play it on the ground and keep holding R and then go into noclip, its gonna play again. This is probably gonna break some stuff.

2.When ``is_on_ground`` has ``affect children only`` **CHECKED* it works, which means nothing changed in this case because it worked before.

**Comment by thegrb93** [comment] 2020-07-23 19:39
Might be good to revert https://github.com/CapsAdmin/pac3/commit/463a65ea05adebbd516c3183bae8029954a6968e if that's the case.

**Comment by thegrb93** [comment] 2020-07-23 19:40
Reopening for now

**Comment by thegrb93** [comment] 2020-07-30 06:09
It didn't work still with your suggestion. Updating to https://github.com/CapsAdmin/pac3/commit/463a65ea05adebbd516c3183bae8029954a6968e fixes it.

**Closed by thegrb93** 2020-07-30 06:09 UTC
Labels: bug

**Comment by Yagira** [comment] 2020-07-30 07:33
Well, explain the video then.

**Comment by thegrb93** [comment] 2020-07-30 07:56
Doesn't look like its working correctly in the video either.

**Comment by thegrb93** [comment] 2020-07-30 07:57
In air and on ground are supposed to be different

**Comment by Yagira** [comment] 2020-07-30 08:09
Why would they be different, the effects are exactly the same, the only difference are the animations that you can't even see without the original model.

**Comment by thegrb93** [comment] 2020-07-30 08:23
The sounds and timing is different I think. The reason you can't tell is because it wasn't working correctly.

**Comment by Yagira** [comment] 2020-07-30 11:01
Yeah you are right, there are different sounds that I didn't notice. Still, is there anything that doesn't work in this file [pac_working.txt](https://github.com/CapsAdmin/pac3/files/5000769/pac_working.txt) in any version before the fix.
