### ISSUE TITLE
Effects are buggy

### ISSUE THREAD

**Issue by ItsLiam21** [CapsAdmin/pac3#423] opened 2017-06-13 15:07 UTC
Whenever i select an effect i can not move it. I can move the directional arrows and stuff but the effect will not follow. Sometimes when i'm finished selecting an effect it just vanishes as well.

**Comment by Earu** [comment] 2017-06-13 16:17
Tick loop and have a model as parent

**Comment by roboderpy** [comment] 2017-08-27 06:14
Duplicate of https://github.com/CapsAdmin/pac3/issues/389

**Closed by roboderpy** 2017-08-27 06:14 UTC
