### ISSUE TITLE
Serverside draw distance overrides persist across servers.

### ISSUE THREAD

**Issue by nerdkoopa** [CapsAdmin/pac3#293] opened 2016-06-08 17:44 UTC
All draw distance overrides set by servers persist across all servers and don't return to the default 0 on servers with that setting, thus rendering all clientside draw distance settings useless. This can be fixed only if the server itself changes the override to an arbitrary number and then back to 0 while the affected player(s) is/are on.

**Comment by LUModder** [comment] 2016-06-08 17:50
Looks to be a duplicate of #284, all I can recommend is wait for next GMod update

**Comment by Fred-FredBurger** [comment] 2016-06-16 22:43
Actually no, its not the exact same.. it's a pac_sv_draw_distance issue.. kinda seems to default to 750 across all servers with pac in it.. the only way to fix that is to set it to 10 and then 0 by super admins or just owners. I've been noticing that myself lately and I dunno wassup.

**Comment by LUModder** [comment] 2016-06-16 22:59
Again, nothing we can do to fix it until next GMod update or the server owners get some common sense.

**Comment by LUModder** [comment] 2016-09-21 00:15
Can be closed, been fixed for a while iirc

**Closed** 2016-09-21 07:34 UTC
Labels: bug
