### ISSUE TITLE
Call nick on invalid player

### ISSUE THREAD

**Issue by FPtje** [CapsAdmin/pac3#177] opened 2015-06-16 08:55 UTC
https://github.com/FPtje/DarkRP/issues/1986

**Comment by LUModder** [comment] 2015-06-16 16:36
PAC is a SANDBOX ADDON FOR A REASON PEOPLE

**Comment by FPtje** [comment] 2015-06-16 16:37
[Fuck off](https://github.com/FPtje/DarkRP/blob/master/gamemode/init.lua#L8)

**Comment by FPtje** [comment] 2015-06-16 16:38
Also, I doubt DarkRP is causing PAC to call `ply:Name()` on a non-existing player.

**Comment by Hazbelll** [comment] 2015-06-16 16:57
http://wiki.garrysmod.com/page/Category:SANDBOX_Hooks

I agree with @FPtje. Considering all of these hooks work without issue in DarkRP, I don't see any reason why PAC shouldn't either. It would be greatly appreciated if this were to be fixed however, as sometimes the "Wear" ability of PAC ceases to function at all anymore and requires a Server restart.

**Comment by CapsAdmin** [comment] 2015-06-16 17:30
Sounds like someone is wearing outfits and then disconnecting right after. There should be valid checks but maybe i missed something.

**Comment by Hazbelll** [comment] 2015-06-16 18:02
I think that could be it. It would make a lot of sense. I've never been able to reproduce this issue on a Test Server alone, but on a Production Server, it will inevitably become an issue, randomly too, between a few hours to a few days, although it did also happen earlier today after I had shut the server down early this morning to do some work on it without any players on at all (although there had been players coming and going the night prior)

**Comment by Hazbelll** [comment] 2015-06-16 18:34
[07:26:04 PM] Dawny: I just read the post
[07:26:14 PM] Dawny: could it be players with auto-wear pacs crashing on join?
[07:29:27 PM] Hazbelll Butterfingers: That too could be a possibility.
[07:29:27 PM] Hazbelll Butterfingers: What do you mean by crashing though?
[07:30:03 PM] Dawny: How when some times you join a server and your game just insta-closes?
[07:30:03 PM] Dawny: That sort of crash.

One of my Admins thinks this could be a possibility. GMod being GMod, it wouldn't be surprising that some people may crash (or "timeout") on join. I've been "timed out" on other servers before that I've had to spend a long time downloading Workshop Addons/FastDL content from.

**Comment by Hazbelll** [comment] 2015-06-16 20:34
```
Dropped "Barista" from server<STEAM_0:1:45178137>
Navarone (Barista) has Left the Server!
[DarkRP] Barista (STEAM_0:1:45178137) disconnected
Atomic Fauna (STEAM_0:0:92730558) Spawned a models/sprops/misc/alphanum/alphanum_d.mdl
[DarkRP] Kittens4Life has been made a Homeless Filly!
[Advert] Digivee: Hungry? Come down to Digivee's Dinner! Best (and only) food in town! Just across from the hospital near the cinema. Se
Toxic killed Mr CarrotV2 using fas2_machete
[DarkRP] Mr CarrotV2 was killed by Toxic with a fas2_machete
Warning: killicon not found 'fas2_machete'
[DarkRP] There is 1 Lua problem!
```
```
Dropped "Vulsegardt" from server<STEAM_0:0:50712346>
ϟ Ultimate Thor ϟ ☠DBN☠ (Vulsegardt) has Left the Server!
[DarkRP] Vulsegardt (STEAM_0:0:50712346) disconnected
[DarkRP] Hitman polish kieubasa accepted a hit on platinumwing77, ordered by Cookie_On_Crack for 500 Gems
[Event] polish kieubasa: hit acc
Mr CarrotV2 (STEAM_0:1:44557967) Spawned a models/props_junk/PlasticCrate01a.mdl
Mr CarrotV2 (STEAM_0:1:44557967) Spawned a models/props_junk/PlasticCrate01a.mdl
Mr CarrotV2 (STEAM_0:1:44557967) Spawned a models/props_junk/PlasticCrate01a.mdl
[DarkRP] There is 1 Lua problem!
```

This just happened on my Server now. The two players who left were wearing PACs. They both left at their own accord. The error printed to Console is exactly the same as the previous ones found at Falco's original post.

So I think you're absolutely correct @CapsAdmin, looks like valid checks are required to prevent this from happening.

**Comment by Hazbelll** [comment] 2015-06-21 18:50
Any updates on this issue? It's really getting out of hand now. Just randomly now:

```
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
```

Literally all there was in my console. DarkRP didn't spit anything out, but I had a look at the Server's Console and it's the exact same issue as before. Really need a fix for this please.

**Comment by CapsAdmin** [comment] 2015-06-22 17:56
maybe pythons fix works? 

reopen if this is still an issue

**Closed by CapsAdmin** 2015-06-22 17:56 UTC

**Comment by Hazbelll** [comment] 2015-06-22 21:25
Thank you both very much. I've not had a chance to try it out yet, but I'll be sure to put it on my Server tomorrow when I wake up during its quiet hours. I'll get back to you at the end of the day and let you know how it got on.

**Comment by Hazbelll** [comment] 2015-06-25 16:40
Just an update on this, the Server's been running for a few days now with the fixed wear.lua file and there's not been a single "Lua problem" since. The fixed you've provided seems to have worked. Thanks!
