### ISSUE TITLE
A few bugs I have experienced that, to my knowledge, haven't been fixed.

### ISSUE THREAD

**Issue by UnknownShifter** [CapsAdmin/pac3#460] opened 2017-08-08 20:40 UTC
1)  If I make a submaterial within a model that shares the same Material ID with that of my entity, it materializes both the model's texture and the ID on the entity.

2)  After a certain amount of making models in pac translucent, they begin to appear at your feet, with no correlating bone despite being technically attached to one.

3)  Using multiple 'command' events with multiple keybinds for separate items causes either both to not work at all, or both to work at the same time with the same key, despite being different things and having different keybinds.

4)  Setting animation rate to 0 doesn't disable animations, it just accelerates them.

5)  Bonemerging a textured object applies the texture to the entirety of your entity.

6)  Sometimes, submaterials flat out do not work.  Not sure of the cause.

7)  Having multiple bodygroups in PAC doesn't seem to work, and rather override eachother.  (I've been able to circumvent this problem by placing the bodygroups within one another, however it can easily get messy and unkempt.)

8)  Whenever something isn't selected, your camera moves and ridiculously fast speeds.  Some sort of cam speed lock would be good so you don't tap W and end up 13000 units out of the map.

I'm sure there are others I have experienced but these are just ones off the top of my head.

**Comment by roboderpy** [comment] 2017-08-28 02:18
1. ??? Please attach your outfit

2. `Translucent` draws on `PostDrawTranslucentRenderables`. Usually you don't need to use `Translucent`, unless model is partially translucent, then you should do that. If model appears at your feet, something is messing with your bones (not PAC3, another addon)

3. Expected behaviour when they trigger at same time. You need to use `equal` check for events then, if you want separated trigger.

4. Animation rate of 0 has special meaning in Source Engine.

5. Use Submaterial. Because of Source Engine Limitations, drawing bonemerged model **always** draws parent first. And if we will reject parent drawing using hooks, parented entity will not be drawed too.

6. ???

7. Duplicate of https://github.com/CapsAdmin/pac3/issues/374

8. Because camera speed is based on distance between camera position and selected part position. But sure, i will fix that.

**Comment by roboderpy** [comment] 2017-09-08 05:50
All of the described is not longer an issues

**Closed by roboderpy** 2017-09-08 05:50 UTC
