### ISSUE TITLE
Material normal maps not working on custom models

### ISSUE THREAD

**Issue by bluemetaknight** [CapsAdmin/pac3#382] opened 2017-02-26 22:01 UTC
When using the material part on custom models, bumpmaps do not work. As seen in this picture, the bumpmap works for the vanilla cube model but doesnt work for the custom model in the background. 
http://imgur.com/zs5hQb7

**Comment by KabusIblis** [comment] 2017-03-28 13:52
I believe it only works on actual mdls that are loaded into the game and not custom models

**Comment by bluemetaknight** [comment] 2017-04-10 02:10
Do you know if there is any way to get them to work on custom models?

**Comment by thegrb93** [comment] 2017-08-19 02:54
I know they used to work. What broke it?

**Comment by thegrb93** [comment] 2017-08-19 03:05
https://github.com/Facepunch/garrysmod-issues/issues/2489

**Comment by roboderpy** [comment] 2017-09-08 05:51
Also duplicate of https://github.com/CapsAdmin/pac3/issues/365

**Closed by roboderpy** 2017-09-08 05:51 UTC
