### ISSUE TITLE
Entity size

### ISSUE THREAD

**Issue by Reginald-Halifrax** [CapsAdmin/pac3#568] opened 2018-01-24 00:21 UTC
Recent attempts to fix the player resize issue remain unfixed, camera remains unchanged to match new height, as well as collisions not shrinking.

**Comment by roboderpy** [comment] 2018-01-24 00:24
Conflicting addon. Disable addons one-by-one until you find conflicting. The (most) likely caused by a custom playermodel addon which adds not-a-human model with different sizes or collision box.

**Comment by Reginald-Halifrax** [comment] 2018-01-24 00:34
didnt have the issue until recently... and this is before and after the supposed fix.

**Comment by roboderpy** [comment] 2018-01-24 00:35
PAC3 only modifies size/view height on part apply. If it doesn't work, some of your addons is changing view height and/or collision box on each game frame.

**Comment by Reginald-Halifrax** [comment] 2018-01-24 00:37
very strange, as i recall the last addon i added (before the issue appeared) was nothing more than a map addon

**Comment by Reginald-Halifrax** [comment] 2018-01-24 00:44
yeah... so just to be positive i disabled literally all addons (just as a control), it seems to remain not working .-.

**Comment by roboderpy** [comment] 2018-01-24 00:45
are you using workshop version of PAC3? try git version (master or develop branch)

**Comment by Reginald-Halifrax** [comment] 2018-01-24 00:46
been using the git master, im going to reinstall it just to be sure

**Comment by Reginald-Halifrax** [comment] 2018-01-24 00:49
still nothing .-.

**Comment by Reginald-Halifrax** [comment] 2018-01-24 00:50
the only error that pac returns as of yet is "[AddCSLuaFile] Couldn't find 'pac3/core/client/drawing.lua' (@addons/pac3-master/lua/autorun/pac_core_init.lua (line 8))
"

**Comment by SladeXanthas** [comment] 2018-01-24 05:17
I've also been having this issue on my server, and I've searched my files, and I'm unable to locate anything that forces player scale.

**Comment by roboderpy** [comment] 2018-01-24 05:19
Fixed in develop

**Closed by roboderpy** 2018-01-24 05:19 UTC
